/**
 * Dependency-free text→PDF renderer for bill captures.
 *
 * LAST RESORT ONLY. A PDF-less bill is normally captured as self-contained HTML
 * and rendered to a real, bill-shaped PDF by `mlgw/capture`; this transcript is
 * what the bills job falls back to when no Chromium is available to render.
 * Because every transcript shares this title block and monospace layout, bills
 * that land here all look alike — that is the degraded mode, not the target.
 *
 * It renders the parsed portal text into a small, valid PDF (Letter pages,
 * Courier body so the bill's column layout survives, bold header + capture
 * note) so EVERY bill can carry an invoice file. The output is deliberately
 * labeled as an Emberly capture of the portal text — it is a transcript, not a
 * reproduction of an MLGW invoice.
 *
 * Hand-rolled on purpose: a text transcript needs ~1% of a PDF library, and
 * the workspace lockfile stays untouched.
 */

export interface BillTextPdfOptions {
  title: string;
  /** Sub-header lines (account, service address, dates…). */
  facts: string[];
  /** The captured bill text; embedded line breaks are honored. */
  text: string;
}

const PAGE_W = 612; // Letter, 72dpi points
const PAGE_H = 792;
const MARGIN = 54;
const BODY_SIZE = 8.5;
const BODY_LEADING = 10.4;
/** Courier at 8.5pt is 5.1pt/char → what fits between the margins. */
const BODY_COLS = Math.floor((PAGE_W - 2 * MARGIN) / (BODY_SIZE * 0.6));

/** PDF string escape (latin-1 subset; anything else becomes "?"). */
function esc(value: string): string {
  let out = "";
  for (const ch of value) {
    const code = ch.codePointAt(0) ?? 63;
    if (ch === "(" || ch === ")" || ch === "\\") out += `\\${ch}`;
    else if (code >= 32 && code <= 255) out += code > 126 ? `\\${code.toString(8).padStart(3, "0")}` : ch;
    else out += "?";
  }
  return out;
}

/** Hard-wrap a line to the body column count, preserving leading indent. */
function wrapLine(line: string): string[] {
  if (line.length <= BODY_COLS) return [line];
  const indent = (line.match(/^\s*/)?.[0] ?? "").slice(0, 16);
  const out: string[] = [];
  let rest = line;
  while (rest.length > BODY_COLS) {
    let cut = rest.lastIndexOf(" ", BODY_COLS);
    if (cut <= indent.length) cut = BODY_COLS;
    out.push(rest.slice(0, cut));
    rest = indent + rest.slice(cut).trimStart();
  }
  out.push(rest);
  return out;
}

export function billTextPdf(options: BillTextPdfOptions): Uint8Array {
  const bodyLines = options.text
    .replaceAll("\r\n", "\n")
    .split("\n")
    .flatMap((line) => wrapLine(line.trimEnd()));

  // Page layout: first page carries the header block, every page the body.
  const headerLines = 3 + options.facts.length; // title + facts + note + gap
  const perPage = Math.floor((PAGE_H - 2 * MARGIN) / BODY_LEADING);
  const pages: string[][] = [];
  let cursor = 0;
  while (cursor < bodyLines.length || pages.length === 0) {
    const capacity = perPage - (pages.length === 0 ? headerLines + 1 : 0);
    pages.push(bodyLines.slice(cursor, cursor + capacity));
    cursor += capacity;
  }

  const contentOf = (page: string[], isFirst: boolean): string => {
    let y = PAGE_H - MARGIN;
    let s = "BT\n";
    if (isFirst) {
      s += `/F2 11 Tf 1 0 0 1 ${MARGIN} ${y} Tm (${esc(options.title)}) Tj\n`;
      y -= 15;
      s += `/F1 ${BODY_SIZE} Tf ${BODY_LEADING} TL 1 0 0 1 ${MARGIN} ${y} Tm\n`;
      for (const fact of options.facts) s += `(${esc(fact)}) Tj T*\n`;
      s += `(${esc("Text capture of the MLGW portal bill page - generated by Emberly (no PDF published by MLGW).")}) Tj T*\n`;
      s += "T*\n";
    } else {
      s += `/F1 ${BODY_SIZE} Tf ${BODY_LEADING} TL 1 0 0 1 ${MARGIN} ${y} Tm\n`;
    }
    for (const line of page) s += `(${esc(line)}) Tj T*\n`;
    s += "ET";
    return s;
  };

  // Object plan: 1 catalog, 2 pages tree, 3 courier, 4 helvetica-bold,
  // then per page: page object + content stream.
  const objects: string[] = [];
  objects.push("<< /Type /Catalog /Pages 2 0 R >>");
  const pageObjIds = pages.map((_, i) => 5 + i * 2);
  objects.push(`<< /Type /Pages /Kids [${pageObjIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>`);
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>");
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
  pages.forEach((page, i) => {
    objects.push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] ` +
        `/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${6 + i * 2} 0 R >>`,
    );
    const content = contentOf(page, i === 0);
    objects.push(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);
  });

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefAt = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) pdf += `${off.toString().padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`;

  // latin-1 encode — esc() already folded everything above 0xFF.
  const bytes = new Uint8Array(pdf.length);
  for (let i = 0; i < pdf.length; i += 1) bytes[i] = pdf.charCodeAt(i) & 0xff;
  return bytes;
}
